Создана база данных с помощью помощника SQL.
Kvantorium16/newground pull request #1
Opened 2021-04-26 08:38 UTC by bulochka14

Добавлена функция на создание и обновление.

2021-04-26 09:17 UTC, Kvantorium16 commented
Сейчас проверю.

2021-04-26 09:27 UTC, Kvantorium16 requested changes
Приму после внесения запрошенных изменений. Новый пулл реквест делать не надо - как только пушнешь новый коммит в свой репозиторий, изменения отобразятся здесь автоматически.

2021-04-26 09:27 UTC, Kvantorium16 commented on app/src/main/java/com/example/newground/db/MyDbHelper.kt
> +       db?.execSQL(MyDbNameClass.CREAT_TABLE)
Не принципиально, но лучше заменить константу _CREAT_TABLE_ на _CREATE_TABLE_.

2021-04-26 09:27 UTC, Kvantorium16 commented on app/src/main/java/com/example/newground/db/MyDbNameClass.kt
> +    const val CREAT_TABLE = "CREATE TABLE IF NOT EXISTS $TABLE_NAME (" +
Не принципиально, но лучше заменить константу _CREAT_TABLE_ на _CREATE_TABLE_.

2021-04-26 09:27 UTC, Kvantorium16 commented on app/src/main/java/com/example/newground/db/MyDbHelper.kt
> +        onCreate(db)
Лучше убрать или закомментировать обе эти строчки. Иначе мы потом будем в недоумении: почему при добавлении новой записи в базу данных она вместо этого удаляется и создаётся заново?

2021-04-26 18:39 UTC, bulochka14 commented on app/src/main/java/com/example/newground/db/MyDbHelper.kt
> +       db?.execSQL(MyDbNameClass.CREAT_TABLE)
Я внесла изменения но не могу сделать push . Выходит это "Push failed
			Invocation failed Unexpected end of file from server"

2021-04-26 19:34 UTC, Kvantorium16 commented on app/src/main/java/com/example/newground/db/MyDbHelper.kt
> +       db?.execSQL(MyDbNameClass.CREAT_TABLE)
Быстрое гугление дало следующие ответы:
1. Вы просто не залогинены в GitHub через Android Studio. Нажмите "Android Studio -> Setting -> GitHub" и залогиньтесь с помощью токена;
2. Если залогиниться не удаётся, переключите настройку в "AndroidStudio -> Preferences -> Git -> SSH Executable" на "Build-in". Это позволит залогиниться без токена, через логин-пароль.

2021-04-27 04:33 UTC, bulochka14 commented on app/src/main/java/com/example/newground/db/MyDbHelper.kt
> +       db?.execSQL(MyDbNameClass.CREAT_TABLE)
Большое спасибо

2021-04-27 06:05 UTC, Kvantorium16 approved these changes

2021-04-27 06:06 UTC, merged